M48
; DRILL file KiCad 10.0.4 date 2026-07-06T13:47:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-06T13:47:14+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X99.0Y-58.5
X156.5Y-58.5
T2
X96.5Y-58.5
X159.0Y-58.5
T3
X107.75Y-51.5
X107.75Y-65.5
X147.75Y-51.5
X147.75Y-65.5
M30
